image: node:5.11.1

pages:
  cache:
    paths:
    - node_modules/
    - bower_components/

  script:
  - npm install gulp -g
  - npm install bower -g
  - npm install
  - bower install --allow-root
  - gulp dist
  - mv dist public
  artifacts:
    paths:
    - public
  only:
    - master
